<p>
    Bienvenido(a) a Garçon.
</p>

<p>
    Ésta es una aplicación con dos propósitos:
    
    <dl>
        <dt>Propósito 1:</dt>
            <dd>Aprender a desarrollar en Zend Framework; en el grupo de 
                PHPCabal.</dd>
        <dt>Propósito 2:</dt>
            <dd>Generar una aplicación que sirva de control de donaciones
                en LinuxCabal, A.C.</dd>
    </dl>
</p>

<p>
    Por lo pronto, está hosteada en GitHub; el repositorio principal es el de
    Renich: <a href="https://github.com/Renich/Garcon">https://github.com/Renich/Garcon</a>.
</p>

<p>
    Por lo pronto, está en construcción. El contenido cambiará mucho y no 
    podemos garantizar que sirva bien. Agradecemos tu comprensión.
</p>
