<html>
    <head>
        <title>Garcon</title>
    </head>

    <body>
        <header>
            <h1>Garcon</h1>
        </header>
<?php echo $this->layout()->content; ?>
        <footer>
            <small>PHPCabal</small>
            <small>|</small>
            <small>HTML5</small>
            <small>|</small>
            <small>CSS3</small>
            <small>|</small>
            <small>Zend Framework 1</small>
            <small>|</small>
            <small>2011</small>
            <small>|</small>
        </footer>  
    </body>
</html>
