<!DOCTYPE html> 
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="es" lang="es"> 
    <head> 
        <!-- Character Set --> 
        <meta charset="utf-8" /> 
 
        <!-- Website's Title --> 
        <title>Garcon</title> 
 
        <!-- Meta --> 
        <meta name="keywords" content="" /> 
        <meta name="description" content="" /> 
 
        <!-- CSS --> 
        <link href="/css/layout.css" media="all" rel="stylesheet" type="text/css"/> 
        <link href="/css/default.css" media="all" rel="stylesheet" type="text/css"/> 
 
        <!-- JS --> 
        <script src="/js/default.js" type="text/javascript"></script> 
        <!--[if IE]>
            <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
        <![endif]--> 
    </head> 

    <body>
        <header>
            <h1>Garcon</h1>
        </header>

        <content>
<?php echo $this->layout()->content; ?>
        </content>

        <footer>
            <small>PHPCabal</small>
            <small>|</small>
            <small>HTML5</small>
            <small>|</small>
            <small>CSS3</small>
            <small>|</small>
            <small>Zend Framework 1</small>
            <small>|</small>
            <small>2011</small>
            <small>|</small>
        </footer>  
    </body>
</html>
