<?php

// setting the controller and action name as title segments:
$request = Zend_Controller_Front::getInstance()->getRequest();
$this->headTitle( $request->getControllerName() );

?>
<?php echo $this->doctype() . "\n"; ?>
<html>
    <head>
        <!-- Meta tags -->
<?php echo $this->headMeta() . "\n"; ?>

        <!-- Title -->
<?php echo ucwords( $this->headTitle() ) . "\n"; ?>

        <!-- CSS, Feeds y favicon -->
<?php echo $this->headLink() . "\n"; ?>

        <!-- jQuery -->
<?php echo $this->partial( '_jquery.phtml' ); ?>
        
        <!-- Javascript -->
<?php echo $this->headScript() . "\n"; ?>
    </head>
    
     <body>
        <!-- Header container -->
        <div id="Header">
<?php echo $this->partial( '_header.phtml' ) . "\n"; ?>

        <!-- Menu container -->
            <div id="Menu">
<?php echo $this->partial( '_nav.phtml' ) . "\n"; ?>
            </div>
            
            <!-- BreadCrumbs container -->
            <div id="BreadCrumbs">
                <span><?php echo $this->navigation()->breadcrumbs()->setMinDepth( 0 ); ?></span>
            </div>
        </div>

        <!-- Content container -->
        <div id="Contenido">
<?php echo $this->partial( '_contenido.phtml' ) . "\n"; ?>
        </div>

        <!-- Footer container -->
        <div id="Footer">
<?php echo $this->partial( '_footer.phtml' ) . "\n"; ?>
        </div>
    </body>
</html>
