<table id="ProductosTabla" >
    <thead>
        <th>Nombre</th>
        <th>Correo</th>
        <th>Telefono</th>
        <th colspan="2">Comandos</th>
    </thead>

    <tbody>
<?php foreach ( $this->clientes as $cliente ) : ?>
        <tr>
            <td><?php echo $this->escape($cliente->nombre); ?></td>
            <td><?php echo $this->escape($cliente->correo); ?></td>
            <td><?php echo $this->escape($cliente->telefono); ?></td>
            <td>editar</td>
            <td>borrar</td>
        </tr>
<?php endforeach; ?>
    </tbody>
</table>
